jobs:
    build:
        docker:
            - image: circleci/node:6.10
        steps:
            - checkout
            - run:
                name: install-dependencies
                command: npm install
            - run:
                name: tests
                command: npm test
            - deploy:
                name: digital-ocean
                command: echo 'deploy joe v1.0'